[project]
name = "telegram-shop-bot"
python_version = "3.11"

[build]
build_command = "python -m pip install --upgrade pip && pip install -r requirements.txt"

[run]
start_command = "python main.py"

[env]
TELEGRAM_TOKEN = "тут_твой_токен"